a = int(input("enter the number"))
b = int(input("enter the number"))
c = int(input("enter the number"))
d = int(input("enter the number"))
e = int(input("enter the number"))
f = int(input("enter the number"))
g = int(input("enter the number"))
h = int(input("enter the number"))
i = int(input("enter the number"))
j = int(input("enter the number"))
print(a+b)
print(c-d)
print(e*f)
print(g%h)
print(i/j)