1.Write a function to generate a random whole number between 0 to 10;

function RandomWholeNumber()
{ 
console.log(Math.round(Math.random() * 10));
} 
RandomWholeNumber();

//------------------------------------------------------------------------//

2.Write a function which will get two parameters and return a sum of it.
function sumofNumbers(a, b)
{ 
console.log(a+b);
}
 sumofNumbers(3, 5);
//------------------------------------------------------------------------//
3. Write a program to create a calculator with all arithmetic operations has functions;

function sumofNumbers(a, b)
{ 
console.log(a+b);
 } 
function subofNumbers(a, b)
{
 console.log(a-b); 
} 
function multiplyofNumbers(a, b)
{ 
console.log(a*b);
 } 
function divideofNumbers(a, b)
{
 console.log(a/b);
 }
 sumofNumbers(5, 8);
 subtractofNumbers(10, 70); 
multiplyofNumbers(10, 124); 
divideofNumbers(12, 9);
 //------------------------------------------------------------------------/

4. Do the following.Create a function to sum two numbers and return the value. Create a function to generate a random number between 0 to 10Pass two values to the sum function, But first value should be passed by the user and the second value should be generated by a random function. /

function sumofNumbers(a, b)
 {
 console.log(a+b);
}
 function generateRandomNumber()
 { 
result = (Math.round(Math.random() * 10)); 
console.log(result); 
return result;
} 
sumofNumbers(2, generateRandomNumber())
